<Project>

  <ItemGroup>
    <PackageVersion Include="ElectronNET.Core" Version="0.5.1" />
    <PackageVersion Include="ElectronNET.Core.AspNet" Version="0.5.1" />
    <PackageVersion Include="LiteDB" Version="5.0.21" />
    <PackageVersion Include="Microsoft.CodeAnalysis.ResxSourceGenerator" Version="5.0.0-1.25277.114" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Porta.Pty" Version="1.0.7" />
    <PackageVersion Include="Radzen.Blazor" Version="11.1.7" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="AwesomeAssertions" Version="9.5.0" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
  </ItemGroup>

</Project>
