using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Act.Core.Agents;

namespace Act.Agents.Codex;

// The four facts this file is built on, each measured against the CLI rather than read from docs.
// `docs/findings/codex-hooks.md` is where they were established and where the wrong turns are
// recorded; what follows is only what a reader has to hold to edit this safely.
//
//   * The profile's `hooks` is a **table whose keys are event names** — `[[hooks.<Event>]]` with a
//     `matcher`, then `[[hooks.<Event>.hooks]]` with a handler. **Not** a string path to a json
//     file: that shape is rejected outright, and rejecting it kills the launch.
//   * A handler's `type` is one of `command`, `prompt`, `agent`, and `command` is a single string.
//   * ACT declares its hooks in its own `--profile` layer and nowhere else. `$CODEX_HOME/hooks.json`
//     is auto-discovered and would work, but it is the *user's* file and ACT will not write it.
//   * Codex hashes each handler definition and re-prompts for trust when it changes, so **the
//     command must be byte-identical on every launch** — which is why the endpoint url and the
//     token ride the process environment instead of appearing in it.
public static class CodexHookConfig
{
    public const string ProfileName = "act";

    // Where Codex records the trust hashes, inside the profile ACT generates. ACT never writes this
    // section and never reads its values — it only has to avoid destroying it.
    public const string TrustStateKey = "[hooks.state";

    public static string ForwarderFileName
        => OperatingSystem.IsWindows() ? "act-hook-forward.cmd" : "act-hook-forward.sh";

    // Session-scoped then turn-scoped, as documented for Codex. `PermissionRequest` is the one
    // Claude Code has no equivalent for, and the reason hooks are worth keeping wired at all: it
    // is an explicit event rather than something to infer from a notification message.
    private static readonly string[] Events =
    [
        "SessionStart",
        "SessionEnd",
        "UserPromptSubmit",
        "PreToolUse",
        "PermissionRequest",
        "PostToolUse",
        "PreCompact",
        "PostCompact",
        "Stop",
    ];

    // `*` throughout. For `SessionStart` the matcher is a source rather than a pattern
    // (`startup` / `resume` / `clear`) and ACT wants every one of them; for the tool events it is
    // a tool-name pattern and ACT observes them all. Both were accepted by the parser.
    private const string AllSources = "*";

    // ACT's profile layer — the only place ACT declares its hooks. Only what ACT owns goes in it;
    // the user's `~/.codex/config.toml` is never edited (Codex itself writes hook-trust state there,
    // under `[hooks.state.…]`, which ACT cannot prevent).
    //
    // Changing this shape is not something to do from the docs: the parser accepts unknown keys in
    // silence, so a wrong shape fails at launch rather than at write. `codex-hooks.md` has
    // the type-probing trick for re-measuring it against a newer CLI.
    public static string ComposeProfile(string forwarderPath, Uri? mcpEndpoint)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# Generated by ACT. Overwritten on every launch; safe to delete.");

        foreach (var name in Events)
        {
            builder.AppendLine();
            builder.AppendLine($"[[hooks.{name}]]");
            builder.AppendLine($"matcher = {Toml(AllSources)}");
            builder.AppendLine();
            builder.AppendLine($"[[hooks.{name}.hooks]]");
            builder.AppendLine("type = \"command\"");
            builder.AppendLine($"command = {Toml(Command(forwarderPath, name))}");
        }

        if (mcpEndpoint is { } endpoint)
            AppendMcpServer(builder, endpoint);

        return builder.ToString();
    }

    // ACT's own MCP server, in the same profile layer as the hooks. Type-probed against the CLI on
    // 2026-08-06 rather than taken from the docs, which only describe `mcp_servers` at config root:
    // `mcp_servers.act.url` wants a string and `mcp_servers.act.env_http_headers` wants a map, both
    // reported by name, so the layer really does parse this table.
    //
    // **`env_http_headers`, never `http_headers`.** It maps a header name to an *environment
    // variable* name, so the per-session token stays on the process environment where the hook
    // forwarder already reads it — and this file stays byte-identical from one launch to the next,
    // which is what the hook-trust hash depends on.
    private static void AppendMcpServer(StringBuilder builder, Uri endpoint)
    {
        builder.AppendLine();
        builder.AppendLine($"[mcp_servers.{McpTransport.ServerName}]");
        builder.AppendLine($"url = {Toml(endpoint.ToString())}");
        builder.AppendLine(
            $"env_http_headers = {{ {Toml(HookTransport.TokenHeader)} = "
                + $"{Toml(AgentEnvironment.ActHookToken)} }}");
    }

    // **The program token must not be quoted, and everything after it may be.** Codex takes quotes
    // literally when it resolves the program, so `"<path>" <Event>` names a program called
    // `"<path>"` — `hook exited with code 1`, script never reached. An unquoted shell with a quoted
    // argument after it works, path with a space included, because from there `cmd` is parsing.
    //
    // This one line is why no Codex hook arrived for the first weeks of the feature; the whole
    // investigation is in `codex-hooks.md`. Do not add quotes around the program.
    private static string Command(string forwarderPath, string eventName)
        => OperatingSystem.IsWindows()
            ? $"{WindowsShell} /c \"{forwarderPath}\" {eventName}"
            : $"/bin/sh \"{forwarderPath}\" {eventName}";

    private static string WindowsShell => Path.Combine(Environment.SystemDirectory, "cmd.exe");

    // A script rather than an inline `curl`, for the hash: the definition names the forwarder and
    // an event, both stable, while everything per-session stays in the environment. A script is
    // also the hedge for the question the findings could not answer — whether Codex interpolates
    // `$VAR` itself or execs without a shell. Read inside a shell, the values resolve either way.
    //
    // Every path exits 0. A hook that fails is a hook that can wedge the user's session, and ACT
    // observes rather than decides: no `permissionDecision`, no `decision: block`, no exit code 2.
    public static string ComposeForwarder()
        => OperatingSystem.IsWindows() ? WindowsForwarder() : PosixForwarder();

    private static string WindowsForwarder()
    {
        var builder = new StringBuilder();

        builder.AppendLine("@echo off");
        builder.AppendLine("setlocal");
        builder.AppendLine("rem Generated by ACT. Reads the payload on stdin and reports it. Always succeeds.");
        builder.AppendLine($"if \"%{AgentEnvironment.ActHookEndpoint}%\"==\"\" exit /b 0");
        builder.AppendLine($"if \"%{AgentEnvironment.ActHookToken}%\"==\"\" exit /b 0");
        builder.AppendLine(
            "curl --silent --show-error --max-time 5 "
                + "--header \"Content-Type: application/json\" "
                + $"--header \"{HookTransport.TokenHeader}: %{AgentEnvironment.ActHookToken}%\" "
                + $"--data-binary @- \"%{AgentEnvironment.ActHookEndpoint}%\" >nul 2>&1");
        builder.AppendLine("exit /b 0");

        return builder.ToString();
    }

    private static string PosixForwarder()
    {
        var builder = new StringBuilder();

        builder.Append("#!/bin/sh\n");
        builder.Append("# Generated by ACT. Reads the payload on stdin and reports it. Always succeeds.\n");
        builder.Append($"[ -n \"${AgentEnvironment.ActHookEndpoint}\" ] || exit 0\n");
        builder.Append($"[ -n \"${AgentEnvironment.ActHookToken}\" ] || exit 0\n");
        builder.Append(
            "curl --silent --show-error --max-time 5 "
                + "--header 'Content-Type: application/json' "
                + $"--header \"{HookTransport.TokenHeader}: ${AgentEnvironment.ActHookToken}\" "
                + $"--data-binary @- \"${AgentEnvironment.ActHookEndpoint}\" >/dev/null 2>&1\n");
        builder.Append("exit 0\n");

        return builder.ToString();
    }

    // A TOML basic string: backslashes **and** quotes both escaped. The quotes matter as much as the
    // separators — the command value wraps the forwarder path in quotes so a path with spaces
    // survives, and leaving those bare produced a file the parser could not read at all.
    private static string Toml(string value)
        => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

    // Codex reads profile layers only out of its own config home, so this is the one path ACT
    // writes outside its own data directory.
    public static string ProfilePath(string codexHome)
        => Path.Combine(codexHome, $"{ProfileName}.config.toml");

    public static string ResolveCodexHome()
    {
        var configured = Environment.GetEnvironmentVariable("CODEX_HOME");

        if (configured is { Length: > 0 })
            return configured;

        return Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".codex");
    }
}
