using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Act.Core.Agents;

namespace Act.Agents.Codex;

// Codex's hooks fire and ACT ingests them, verified live 2026-07-31 on `codex-cli
// 0.146.0-alpha.3.1` — which reverses the finding this file was written blind under. The
// `exited with code 1` that made them look dead was ACT quoting the program token; see `Command`.
//
// Facts this file depends on, each measured against the CLI rather than read from docs:
//   * The profile's `hooks` is a **table whose keys are event names**, each a list of matcher
//     groups — `[[hooks.<Event>]]` with `matcher`, then `[[hooks.<Event>.hooks]]` with a handler.
//     It is **not** a string path to a json file; that shape is what the CLI now rejects.
//   * A handler's `type` is one of `command`, `prompt`, `agent`, and `command` is a single string.
//   * `$CODEX_HOME/hooks.json` is auto-discovered on its own — `{ "hooks": { "<Event>": [ … ] } }`,
//     BOM-free — so the json and the profile are two independent ways in. ACT writes the json into
//     its own data directory (never over the user's) and declares the same handlers in its profile.
//   * Codex hashes each handler definition and re-prompts for trust when it changes — so the
//     command below must be byte-identical on every launch, which is why the endpoint url and
//     the token are read from the process environment instead of appearing in it.
public static class CodexHookConfig
{
    public const string ProfileName = "act";

    public const string HooksFileName = "act-hooks.json";

    // Where Codex records the trust hashes, inside the profile ACT generates. ACT never writes this
    // section and never reads its values — it only has to avoid destroying it.
    public const string TrustStateKey = "[hooks.state";

    public static string ForwarderFileName
        => OperatingSystem.IsWindows() ? "act-hook-forward.cmd" : "act-hook-forward.sh";

    // Session-scoped then turn-scoped, as documented for Codex. `PermissionRequest` is the one
    // Claude Code has no equivalent for, and the reason hooks are worth keeping wired at all: it
    // is an explicit event rather than something to infer from a notification message.
    private static readonly string[] Events =
    [
        "SessionStart",
        "SessionEnd",
        "UserPromptSubmit",
        "PreToolUse",
        "PermissionRequest",
        "PostToolUse",
        "PreCompact",
        "PostCompact",
        "Stop",
    ];

    // `*` throughout. For `SessionStart` the matcher is a source rather than a pattern
    // (`startup` / `resume` / `clear`) and ACT wants every one of them; for the tool events it is
    // a tool-name pattern and ACT observes them all. Both were accepted by the parser.
    private const string AllSources = "*";

    public static string ComposeHooks(string forwarderPath)
    {
        var events = new JsonObject();

        foreach (var name in Events)
        {
            events[name] = new JsonArray(
                new JsonObject
                {
                    ["matcher"] = AllSources,
                    ["hooks"] = new JsonArray(
                        new JsonObject
                        {
                            ["type"] = "command",
                            ["command"] = Command(forwarderPath, name),
                        }),
                });
        }

        var document = new JsonObject
        {
            ["description"] = "ACT — observability only. Reports to ACT; never blocks a turn.",
            ["hooks"] = events,
        };

        return document.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
    }

    // ACT's profile layer, declaring the same handlers the json file does. Only what ACT owns goes in
    // it — the user's `~/.codex/config.toml` is never edited by ACT (Codex itself writes hook-trust
    // state there, under `[hooks.state.…]`, which ACT cannot prevent).
    //
    // The shape was **measured on 2026-07-31**, after the previous one (`hooks = "<path>"`) turned out
    // to make the CLI refuse to start at all and killed every Codex launch. How it was pinned down,
    // since the parser ignores unknown keys and would accept a wrong shape in silence: give a known
    // field the wrong *type* and serde names it. `hooks.state = 1` → "expected a map";
    // `hooks.SessionStart = 1` → "expected a sequence"; `matcher = 1` → "expected a string";
    // `type = "bogus"` → "unknown variant `bogus`, expected one of `command`, `prompt`, `agent`".
    public static string ComposeProfile(string forwarderPath)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# Generated by ACT. Overwritten on every launch; safe to delete.");

        foreach (var name in Events)
        {
            builder.AppendLine();
            builder.AppendLine($"[[hooks.{name}]]");
            builder.AppendLine($"matcher = {Toml(AllSources)}");
            builder.AppendLine();
            builder.AppendLine($"[[hooks.{name}.hooks]]");
            builder.AppendLine("type = \"command\"");
            builder.AppendLine($"command = {Toml(Command(forwarderPath, name))}");
        }

        return builder.ToString();
    }

    // One string, identical to what the json file declares — the definition is hashed for trust, so
    // the two must not drift.
    //
    // **The program token must not be quoted, and everything after it may be.** Measured
    // 2026-07-31 by giving five events five candidate shapes and reading which ones ran: Codex takes
    // quotes literally when it resolves the program, so `"<path>" <Event>` is a program named
    // `"<path>"`, which does not exist — `hook exited with code 1`, with the script never reached.
    // ACT quoted the path from the first launch it ever made, which is why no Codex hook had ever
    // arrived. An *unquoted* path runs, and so does an unquoted shell with a quoted argument after
    // it — including a path containing a space, because at that point `cmd` is doing the parsing.
    private static string Command(string forwarderPath, string eventName)
        => OperatingSystem.IsWindows()
            ? $"{WindowsShell} /c \"{forwarderPath}\" {eventName}"
            : $"/bin/sh \"{forwarderPath}\" {eventName}";

    private static string WindowsShell => Path.Combine(Environment.SystemDirectory, "cmd.exe");

    // A script rather than an inline `curl`, for the hash: the definition names the forwarder and
    // an event, both stable, while everything per-session stays in the environment. A script is
    // also the hedge for the question the findings could not answer — whether Codex interpolates
    // `$VAR` itself or execs without a shell. Read inside a shell, the values resolve either way.
    //
    // Every path exits 0. A hook that fails is a hook that can wedge the user's session, and ACT
    // observes rather than decides: no `permissionDecision`, no `decision: block`, no exit code 2.
    public static string ComposeForwarder()
        => OperatingSystem.IsWindows() ? WindowsForwarder() : PosixForwarder();

    private static string WindowsForwarder()
    {
        var builder = new StringBuilder();

        builder.AppendLine("@echo off");
        builder.AppendLine("setlocal");
        builder.AppendLine("rem Generated by ACT. Reads the payload on stdin and reports it. Always succeeds.");
        builder.AppendLine($"if \"%{AgentEnvironment.ActHookEndpoint}%\"==\"\" exit /b 0");
        builder.AppendLine($"if \"%{AgentEnvironment.ActHookToken}%\"==\"\" exit /b 0");
        builder.AppendLine(
            "curl --silent --show-error --max-time 5 "
                + "--header \"Content-Type: application/json\" "
                + $"--header \"{HookTransport.TokenHeader}: %{AgentEnvironment.ActHookToken}%\" "
                + $"--data-binary @- \"%{AgentEnvironment.ActHookEndpoint}%\" >nul 2>&1");
        builder.AppendLine("exit /b 0");

        return builder.ToString();
    }

    private static string PosixForwarder()
    {
        var builder = new StringBuilder();

        builder.Append("#!/bin/sh\n");
        builder.Append("# Generated by ACT. Reads the payload on stdin and reports it. Always succeeds.\n");
        builder.Append($"[ -n \"${AgentEnvironment.ActHookEndpoint}\" ] || exit 0\n");
        builder.Append($"[ -n \"${AgentEnvironment.ActHookToken}\" ] || exit 0\n");
        builder.Append(
            "curl --silent --show-error --max-time 5 "
                + "--header 'Content-Type: application/json' "
                + $"--header \"{HookTransport.TokenHeader}: ${AgentEnvironment.ActHookToken}\" "
                + $"--data-binary @- \"${AgentEnvironment.ActHookEndpoint}\" >/dev/null 2>&1\n");
        builder.Append("exit 0\n");

        return builder.ToString();
    }

    // A TOML basic string: backslashes **and** quotes both escaped. The quotes matter as much as the
    // separators — the command value wraps the forwarder path in quotes so a path with spaces
    // survives, and leaving those bare produced a file the parser could not read at all.
    private static string Toml(string value)
        => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

    // Codex reads profile layers only out of its own config home, so this is the one path ACT
    // writes outside its own data directory.
    public static string ProfilePath(string codexHome)
        => Path.Combine(codexHome, $"{ProfileName}.config.toml");

    public static string ResolveCodexHome()
    {
        var configured = Environment.GetEnvironmentVariable("CODEX_HOME");

        if (configured is { Length: > 0 })
            return configured;

        return Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".codex");
    }
}
