using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Act.Core.Agents;

namespace Act.Agents.Codex;

// PENDING — WRITTEN BLIND. Codex hooks do not fire at all on `codex-cli 0.146.0-alpha.3.1`:
// discovered and parsed, never executed. Everything here is shaped to what the measurements say
// *should* work and has never been observed working. Do not treat a silent Codex card as proof
// this file is correct — read `docs/codex-hooks-findings.md` first, then run its re-test
// checklist against a newer CLI. Upstream: https://github.com/openai/codex/issues/17532
//
// Three facts the findings pinned down, each of which this file depends on:
//   * `hooks` in config.toml is a *string path* to a json file, not a `[[hooks.*]]` table.
//   * The json is `{ "hooks": { "<Event>": [ { "matcher": …, "hooks": [handler…] } ] } }`,
//     the handler's `command` is a single string, and the file must be BOM-free.
//   * Codex hashes each handler definition and re-prompts for trust when it changes — so the
//     command below must be byte-identical on every launch, which is why the endpoint url and
//     the token are read from the process environment instead of appearing in it.
public static class CodexHookConfig
{
    public const string ProfileName = "act";

    public const string HooksFileName = "act-hooks.json";

    public static string ForwarderFileName
        => OperatingSystem.IsWindows() ? "act-hook-forward.cmd" : "act-hook-forward.sh";

    // Session-scoped then turn-scoped, as documented for Codex. `PermissionRequest` is the one
    // Claude Code has no equivalent for, and the reason hooks are worth keeping wired at all: it
    // is an explicit event rather than something to infer from a notification message.
    private static readonly string[] Events =
    [
        "SessionStart",
        "SessionEnd",
        "UserPromptSubmit",
        "PreToolUse",
        "PermissionRequest",
        "PostToolUse",
        "PreCompact",
        "PostCompact",
        "Stop",
    ];

    // `*` throughout. For `SessionStart` the matcher is a source rather than a pattern
    // (`startup` / `resume` / `clear`) and ACT wants every one of them; for the tool events it is
    // a tool-name pattern and ACT observes them all. Both were accepted by the parser.
    private const string AllSources = "*";

    public static string ComposeHooks(string forwarderPath)
    {
        var events = new JsonObject();

        foreach (var name in Events)
        {
            events[name] = new JsonArray(
                new JsonObject
                {
                    ["matcher"] = AllSources,
                    ["hooks"] = new JsonArray(
                        new JsonObject
                        {
                            ["type"] = "command",
                            ["command"] = $"\"{forwarderPath}\" {name}",
                        }),
                });
        }

        var document = new JsonObject
        {
            ["description"] = "ACT — observability only. Reports to ACT; never blocks a turn.",
            ["hooks"] = events,
        };

        return document.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
    }

    // ACT's profile layer. Only what ACT owns goes in it — the user's `~/.codex/config.toml` is
    // never edited by ACT (Codex itself writes hook-trust state there, which ACT cannot prevent).
    public static string ComposeProfile(string hooksFilePath)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# Generated by ACT. Overwritten on every launch; safe to delete.");
        builder.AppendLine($"hooks = {Toml(hooksFilePath)}");

        return builder.ToString();
    }

    // A script rather than an inline `curl`, for the hash: the definition names the forwarder and
    // an event, both stable, while everything per-session stays in the environment. A script is
    // also the hedge for the question the findings could not answer — whether Codex interpolates
    // `$VAR` itself or execs without a shell. Read inside a shell, the values resolve either way.
    //
    // Every path exits 0. A hook that fails is a hook that can wedge the user's session, and ACT
    // observes rather than decides: no `permissionDecision`, no `decision: block`, no exit code 2.
    public static string ComposeForwarder()
        => OperatingSystem.IsWindows() ? WindowsForwarder() : PosixForwarder();

    private static string WindowsForwarder()
    {
        var builder = new StringBuilder();

        builder.AppendLine("@echo off");
        builder.AppendLine("setlocal");
        builder.AppendLine("rem Generated by ACT. Reads the payload on stdin and reports it. Always succeeds.");
        builder.AppendLine($"if \"%{AgentEnvironment.ActHookEndpoint}%\"==\"\" exit /b 0");
        builder.AppendLine($"if \"%{AgentEnvironment.ActHookToken}%\"==\"\" exit /b 0");
        builder.AppendLine(
            "curl --silent --show-error --max-time 5 "
                + "--header \"Content-Type: application/json\" "
                + $"--header \"{HookTransport.TokenHeader}: %{AgentEnvironment.ActHookToken}%\" "
                + $"--data-binary @- \"%{AgentEnvironment.ActHookEndpoint}%\" >nul 2>&1");
        builder.AppendLine("exit /b 0");

        return builder.ToString();
    }

    private static string PosixForwarder()
    {
        var builder = new StringBuilder();

        builder.Append("#!/bin/sh\n");
        builder.Append("# Generated by ACT. Reads the payload on stdin and reports it. Always succeeds.\n");
        builder.Append($"[ -n \"${AgentEnvironment.ActHookEndpoint}\" ] || exit 0\n");
        builder.Append($"[ -n \"${AgentEnvironment.ActHookToken}\" ] || exit 0\n");
        builder.Append(
            "curl --silent --show-error --max-time 5 "
                + "--header 'Content-Type: application/json' "
                + $"--header \"{HookTransport.TokenHeader}: ${AgentEnvironment.ActHookToken}\" "
                + $"--data-binary @- \"${AgentEnvironment.ActHookEndpoint}\" >/dev/null 2>&1\n");
        builder.Append("exit 0\n");

        return builder.ToString();
    }

    private static string Toml(string value) => $"\"{value.Replace("\\", "\\\\")}\"";

    // Codex reads profile layers only out of its own config home, so this is the one path ACT
    // writes outside its own data directory.
    public static string ProfilePath(string codexHome)
        => Path.Combine(codexHome, $"{ProfileName}.config.toml");

    public static string ResolveCodexHome()
    {
        var configured = Environment.GetEnvironmentVariable("CODEX_HOME");

        if (configured is { Length: > 0 })
            return configured;

        return Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".codex");
    }
}
